DROP TABLE IF EXISTS video_games;
DROP TABLE IF EXISTS game_console;
DROP TABLE IF EXISTS game_retailers;

CREATE TABLE video_games (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    genre TEXT NOT NULL,
    rating SMALLINT
);

CREATE TABLE game_console (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    console_company TEXT
);

CREATE TABLE game_retailers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    name TEXT NOT NULL,
    url VARCHAR(255)
);

